export const API_ROUTES = {
  EVENT: '/api/event',
  TASKS: '/api/tasks',
  PROVIDERS: '/api/providers',
  GUESTS: '/api/guests',
  GUESTS_DELETE_ALL: '/api/guests/delete-all',
  GUESTS_IMPORT: '/api/guests/import',
  SHOPPING: '/api/shopping',
  GIFTS: '/api/gifts',
  INVITATION: '/api/invitation',
  PUBLIC_NOTES: '/api/public-notes',
  INVITE_USER: '/api/invite-user',
  INVITE_ACCEPT: '/api/invite-user/accept',
  EVENT_MEMBERS: '/api/event-members',
  MY_EVENTS: '/api/my-events',
}
