const MAZAL_TOV_TODOS_KEY = "todosMazalTov"
const MAZAL_TOV_PROVIDERS_KEY = "providersMazalTov"
const MAZAL_TOV_INCOMES_KEY = "incomesMazalTov"
const MAZAL_TOV_GUESTS_KEY = "guestsMazalTov"
const MAZAL_TOV_EVENT_SETTINGS_KEY = "eventSettingsMazalTov"

export {
  MAZAL_TOV_TODOS_KEY,
  MAZAL_TOV_PROVIDERS_KEY,
  MAZAL_TOV_INCOMES_KEY,
  MAZAL_TOV_GUESTS_KEY,
  MAZAL_TOV_EVENT_SETTINGS_KEY,
}