const MAZAL_TOV_TODOS_KEY = "todosMazalTov"
const MAZAL_TOV_PROVIDERS_KEY = "providersMazalTov"
const MAZAL_TOV_INCOMES_KEY = "incomesMazalTov"
const MAZAL_TOV_GUESTS_KEY = "guestsMazalTov"

export { MAZAL_TOV_TODOS_KEY, MAZAL_TOV_PROVIDERS_KEY, MAZAL_TOV_INCOMES_KEY, MAZAL_TOV_GUESTS_KEY }